apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  config.xml: |-
    <yandex>
      <!-- Listen wildcard address to allow accepting connections from other containers and host network. -->
      <listen_host>0.0.0.0</listen_host>
      <listen_try>1</listen_try>

      <logger>
          <console>1</console>
      </logger>
    </yandex>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server:19.4
        ports:
        - containerPort: 8123
        - containerPort: 9009
        - containerPort: 9000
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/config.d
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
      volumes:
      - name: clickhouse-config
        configMap:
          name: clickhouse-config
          items:
          - key: config.xml
            path: config.xml
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: default
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  type: ClusterIP
  ports:
  - protocol: TCP
    name: clickhouse
    port: 8123
    targetPort: 8123
  - protocol: TCP
    name: clickhouse-2
    port: 9009
    targetPort: 9009
  - protocol: TCP
    name: clickhouse-3
    port: 9000
    targetPort: 9000