apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-worker
  labels:
    app: sentry-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentry-worker
  template:
    metadata:
      labels:
        app: sentry-worker
    spec:
      containers:
      - name: sentry-worker
        image: {{ .Values.SENTRY_IMAGE }}
        command: ["sentry"]
        args: ["run", "worker"]
        resources:
          limits:
            cpu: 0.5
            memory: 350Mi
          requests:
            cpu: 250m
            memory: 150Mi
        env:
        - name: SNUBA
          value: 'http://snuba-api:1218'
        - name: SENTRY_SECRET_KEY
          value: {{ .Values.SENTRY_SECRET_KEY }}
        - name: SENTRY_POSTGRES_HOST
          value: {{ .Values.SENTRY_POSTGRES_HOST }}
        - name: SENTRY_DB_NAME
          value: {{ .Values.SENTRY_DB_NAME }}
        - name: SENTRY_DB_USER
          value: {{ .Values.SENTRY_DB_USER }}
        - name: SENTRY_DB_PASSWORD
          value: {{ .Values.SENTRY_DB_PASSWORD }}
        - name: C_FORCE_ROOT
          value: "1"