apiVersion: apps/v1
kind: Deployment
metadata:
  name: snuba-api
  labels:
    app: snuba-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snuba-api
  template:
    metadata:
      labels:
        app: snuba-api
    spec:
      containers:
      - name: snuba-api
        image: getsentry/snuba:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1218
        env:
        - name: SNUBA_SETTINGS
          value: docker
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: DEFAULT_BROKERS
          value: sentry-kafka:9092
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: snuba-api
spec:
  selector:
    app: snuba-api
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 1218
    targetPort: 1218
